In [1]:
import numpy as np
from nms2d import nms2d
from nms3d import nms3d

In [2]:
ran = np.random.randint(10,size = (6,8))
ran

array([[6, 4, 4, 1, 7, 1, 2, 6],
       [9, 0, 2, 1, 0, 6, 8, 9],
       [8, 0, 8, 1, 4, 9, 6, 9],
       [6, 5, 8, 4, 2, 1, 5, 7],
       [7, 2, 7, 5, 1, 1, 8, 6],
       [6, 1, 0, 8, 1, 0, 9, 4]])

In [3]:
ran2 = nms2d(ran)
ran2

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [4]:
x = np.nonzero(ran2)

In [5]:
x

(array([2, 2, 3], dtype=int64), array([2, 5, 2], dtype=int64))

In [6]:
len(x)

2

In [7]:
x[1].shape[0]

3

In [8]:
rand = np.random.randint(0,10, size = (6,4,5))
rand

array([[[3, 0, 2, 7, 6],
        [5, 0, 6, 8, 5],
        [0, 5, 1, 1, 6],
        [5, 4, 7, 7, 4]],

       [[7, 2, 5, 5, 9],
        [2, 9, 7, 9, 2],
        [4, 4, 6, 3, 2],
        [1, 6, 3, 0, 1]],

       [[4, 8, 6, 0, 9],
        [7, 0, 8, 0, 3],
        [4, 6, 4, 3, 2],
        [4, 3, 3, 3, 7]],

       [[0, 8, 4, 9, 9],
        [0, 9, 2, 1, 2],
        [7, 4, 2, 6, 8],
        [2, 8, 8, 6, 7]],

       [[3, 9, 3, 0, 8],
        [0, 0, 1, 7, 3],
        [9, 1, 4, 1, 2],
        [5, 4, 4, 0, 1]],

       [[9, 2, 7, 3, 3],
        [4, 9, 2, 5, 7],
        [5, 5, 8, 3, 8],
        [8, 2, 6, 3, 9]]])

In [9]:
rand2 = np.copy(rand)
for i in range(len(rand)):
    print("Slice number:",i)
    rand2[i] = nms2d(rand[i])
rand2

Slice number: 0
Slice number: 1
Slice number: 2
Slice number: 3
Slice number: 4
Slice number: 5


array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 1, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [10]:
rand3 = nms3d(rand2, rand)

length of binary array: 6
slice number: 0
length of nonzero output array: 2
length of the tuple is: 1
index of the maxima location to be checked: 0
length of nonzero output array: 2
length of the tuple is: 0
slice number: 1
length of nonzero output array: 2
length of the tuple is: 2
index of the maxima location to be checked: 0
index of the maxima location to be checked: 1
slice number: 2
length of nonzero output array: 2
length of the tuple is: 1
index of the maxima location to be checked: 0
slice number: 3
length of nonzero output array: 2
length of the tuple is: 1
index of the maxima location to be checked: 0
slice number: 4
length of nonzero output array: 2
length of the tuple is: 0
slice number: 5
length of nonzero output array: 1
length of the tuple is: 0
(array([], dtype=int64),)


In [11]:
rand3

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 0, 1, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])